# Generated by Django 5.2.1 on 2026-05-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Client/Company name', max_length=100)),
                ('logo', models.ImageField(help_text='Client logo image (preferably PNG with transparent bg)', upload_to='clients/')),
                ('website_url', models.URLField(blank=True, help_text='Optional client website link', null=True)),
                ('order', models.IntegerField(default=0, help_text='Order in scrolling belt (lower = appears earlier)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this client on website')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['order'],
            },
        ),
    ]
