# Generated by Django 5.2.1 on 2026-05-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='location',
            field=models.CharField(blank=True, help_text='City or region name shown on the India map tooltip', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='map_x',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Horizontal map position on the India map, as a percentage (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='map_y',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Vertical map position on the India map, as a percentage (0-100)', max_digits=5, null=True),
        ),
    ]
