# Generated by Django 5.2.1 on 2026-05-30 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('days_to_complete', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, help_text='Optional summary like "3 months", "6 weeks", or "1 year"', max_length=100)),
                ('time_taken', models.DurationField(blank=True, help_text='Total time taken for the project, for example 45 days of work.', null=True)),
                ('order', models.IntegerField(default=0, help_text='Lower values appear first')),
                ('is_active', models.BooleanField(default=True, help_text='Show this project on the about timeline')),
            ],
            options={
                'verbose_name': 'About Project',
                'verbose_name_plural': 'About Projects',
                'ordering': ['order', '-start_date'],
            },
        ),
    ]
