# Generated by Django 5.2.1 on 2026-05-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutproject',
            name='year',
            field=models.IntegerField(blank=True, help_text='Project year (e.g., 2024)', null=True),
        ),
    ]
