# Generated by Django 5.2.1 on 2026-05-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutproject_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutproject',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Full in-depth project description'),
        ),
        migrations.AddField(
            model_name='aboutproject',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='aboutproject',
            name='project_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
